### ISSUE TITLE
Investigating about Toggle Api

### ISSUE THREAD

**Issue by mahyaa** [lunatech-labs/teahub#12]
The hours that are spend per project needed to add in Toggle via Toggle webpage. In TEAHub, per project we are going to have estimation time and real spend time. The spending time needed to be loaded from Toggle. Therefore, we need to know how does Toggle Api works and what kind of information it gives us. For instance does it also return the bill info along with the hours?

**Comment by pepite** [comment]
You can have a look at the Leslie project where we use the toggl API. Ping fransico.

**Comment by mahyaa** [comment]
thank you @pepite

**Comment by mahyaa** [comment]
All the information about Toggl APi can be find here:
https://github.com/toggl/toggl_api_docs/blob/master/toggl_api.md

loading projects name needs workspace ID and api token. Loading spending time needs api token (you can get this from requesting time entries)
