### ISSUE TITLE
Investigation about CI and test coverage 

### ISSUE THREAD

**Issue by mahyaa** [lunatech-labs/teahub#7]
There are plenty of options for CI, some of them gives the ability for the test coverage too. For instance: Bamboo, CircleCI, TeamCity, etc. Right now our first suggestion for CI is Travis. However, Travis does not have the option for test coverage. 
An investigation is needed in this area to know what is the best option.

**Comment by vijaykiran** [comment]
We can use https://codeclimate.com for test coverage.

**Comment by mahyaa** [comment]
We will use Travis. We will deal with TC  later.
